### PR TITLE
Call PlayerMoveEvent

### PR DESCRIPTION
**Pull request by dequis**
Based on JeromSar's code, with several improvements

Particularly, the event isn't called if both locations are equal. This decreases event spam but not as much as craftbukkit does - that would require keeping state in the player of the last sent move event, which would be awkward.

[MiniPython](https://github.com/SpaceManiac/MiniPython) test plugin here: https://gist.github.com/dequis/0c05ebfa93cf9984f877

### CODE REVIEW

**Comment by turt2live** [comment]
For those who don't want to compile things or dig for a download link, [slightly different testing materials](https://drive.google.com/folderview?id=0B6JIYSBkLkAnV0luYUloSHFMLW8&usp=sharing&tid=0B6JIYSBkLkAnTTZYd3Z4ZTMzV3c)

**Comment by turt2live** [comment]
@dequis This does not correctly handle the case of a plugin setting the from/to properties. The 'from' property won't do anything until some kind of "You moved too fast" code is implemented, but the 'to' property should move the player there after the event, which is fairly obvious.

**Comment by SpaceManiac** [comment]
Merged in ~~6cafd1d~~ 281e3c1.

**Comment by bendem** [comment]
in 281e3c1b7a49d84e904511b9038ee1adc13e9d44 :wink:

**Pull request closed without merging**
