### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by Grinch**
- Add 'mavenLocal' to repository list.
- Specify to not include '-shadow' in the JAR name in /build/distributions/.
- Specify default tasks to perform, now you can just run 'gradle' (or 'gradlew'/'gradlew.bat')

Signed-off-by: Steven Downer grinch@outlook.com

### CODE REVIEW

**Comment by SpaceManiac** [comment]
Is there a reason you duplicate JUnit as both compile and testCompile? Other than that, I think the changes look good.

**Comment by lukespragg** [comment]
You don't need JUnit in the final shadow jar, so testCompile should be all you need. @Grinch?

**Comment by Grinch** [comment]
Yeah, not sure why I added that. Fixed now though.

**Comment by SpaceManiac** [comment]
Merged in 8b359f61e545377d32d10661ff62d610d5c10665.

**Pull request closed without merging**
