### PR TITLE
Add effects from 1.7

### PR DESCRIPTION
**Pull request by socram8888**
Complementary to https://github.com/GlowstoneMC/Glowkit/pull/13

---

_Edited by turt2live_

**Related Links:**
- Glowkit: GlowstoneMC/Glowkit#13
- No ticket (none needed)

### CODE REVIEW

**Comment by Nickforall** [comment]
@MeltedLux because it needs a change in GlowKit, where he made a PR for too.
GlowstoneMC/Glowkit#13

**Comment by gdude2002** [comment]
Just to confirm - with [Glowkit PR 13](https://github.com/GlowstoneMC/Glowkit/pull/13), this does indeed appear to build perfectly. http://bamboo.gserv.me/browse/GLOW-SRV-PR289-47

**Comment by gdude2002** [comment]
Broken as of the Lombok commit. http://bamboo.gserv.me/browse/GLOW-SRV-PR289-49

EDIT: Ignore that, forgot to update build.gradle - http://bamboo.gserv.me/browse/GLOW-SRV-PR289-51

**Comment by turt2live** [comment]
The glowkit PR adds a bunch of effects, but this PR only implements one. Is there a particular reason for that?

**Comment by SpaceManiac** [comment]
Implementations in `GlowEffect` are only needed for effects which have data attached, and `LAND_DUST` is the only one of those added in the Glowkit PR that has that.

**Comment by turt2live** [comment]
While testing I could not get the following effects to work:
- Enderdragon death
- Bonemeal use
- Land dust

**Comment by turt2live** [comment]
@socram8888 Friendly reminder that changes are needed on this PR (or proof that I'm just being an idiot with my last message)

**Comment by socram8888** [comment]
I'll need to decompile the handler on the client side. I'll see if they've changed something, since well, this was for 1.7.

**Comment by socram8888** [comment]
Okay, LAND_DUST has been removed (I guess it's now generated on the client side).
I'm guessing that the enderdragon cry isn't working because I haven't set the isDistanceIgnored (it wasn't set here originally either, so I thought it wasn't needed).

**Comment by socram8888** [comment]
Okay, Enderdragon should work now.

I don't know why the bonemeal effect isn't working, however. This is the code that's supposed to handle the effect:

``` java
   public static void a(aqu var0, dt var1, int particleCount) {
      if(particleCount == 0) {
         particleCount = 15;
      }

      atr var3 = var0.p(var1).c();
      if(var3.r() != bof.a) {
         var3.a((ard)var0, var1);

         for(int i = 0; i < particleCount; i++) {
            double var5 = g.nextGaussian() * 0.02D;
            double var7 = g.nextGaussian() * 0.02D;
            double var9 = g.nextGaussian() * 0.02D;
            var0.spawnParticle(ParticleType.VILLAGER_HAPPY, (double)((float)var1.n() + g.nextFloat()), (double)var1.o() + (double)g.nextFloat() * var3.C(), (double)((float)var1.p() + g.nextFloat()), var5, var7, var9, new int[0]);
         }

      }
   }
```

It has some kind of validation (`if(var3.r() != bof.a) {`), but I don't know what's it doing.

**Comment by turt2live** [comment]
@socram8888 Your sample block shows `VILLAGER_HAPPY`, not `BONEMEAL`, did you mean something else?

**Comment by socram8888** [comment]
Nope. It's VILLAGER_HAPPY for sure (it's from an "enum" class, and the obfuscator Mojang uses doesn't remove the original name from enums)

Anyway, note that it's the same particle (http://minecraft.gamepedia.com/Particles)

**Comment by dequis** [comment]
Leaving it out of the PR is an option, I guess.

BTW, merge with master to get an updated .travis.yml that should make the build pass :3

**Comment by jimmikaelkael** [comment]
@socram8888 
if(var3.r() != bof.a is an AIR block material check: if(var3.getType() != Material.AIR
However I doubt it can really help you...

**Comment by jimmikaelkael** [comment]
I found the problem. It's that the bonemeal is not an effect but rather a particle and it's not the same packet that should be sent.

EDIT:
I think you should modify your GlowKit PR to remove all things that are particles (BONEMEAL_USE) as it can be played with Player.showParticle().

**Comment by socram8888** [comment]
Nope. HAPPY_VILLAGER is a particle but BONEMEAL_USE is a visual effect.

**Comment by jimmikaelkael** [comment]
After checking it again you're right on the fact Effect 2005 is used, but I'm right when I say it's a different protocol packet.

EDIT: forget it I'm an idiot.

**Comment by turt2live** [comment]
Just as a note: NMS/Other implementations are to be used as reference and not be cloned, duplicated, and/or copy/pasted into Glowstone/Glowkit. This is not only considered bad practice, but has some legal implications as well. Referencing the aforementioned code is fine for filling gaps in how things should operate but should not be used as a dependent source for the basis of a PR.

Generally you would want to try the feature yourself on the Mojang server. If that doesn't describe the behaviour you would point yourself to other resources such as the various (and official) Minecraft wikis. At that point if you still have questions or concerns, then you would move to some source code to determine what is going on.

I am not accusing this PR of anything at this time. I just noticed a lot of talk about other implementations and thought I should make it clear on how to proceed with those resources.

**Comment by socram8888** [comment]
"NMC" stuff I pasted is from the client, it's of no help when developing the server. That's the only reference I've used, straight from a FernFlower decompilation of the said binary.

**Comment by jimmikaelkael** [comment]
The best person to ask would be md_5, it's somewhat kind of strange that he didn't implemented effect 2005 and is rather using another protocol packet. There must be a good reason behing that.

One possible reason for that 2005 value being like handled by the client maybe a bad code cleanup on mojang side.

**Comment by socram8888** [comment]
So I've finally written a test plugin. BONEMEAL_USE it's working perfectly
BONEMEAL_USE on pressure plate

**Comment by jimmikaelkael** [comment]
Great ^^ 
I'll use that then in my bonemeal interaction PR.

If I understand it well, bonemeal effect can't be played in air, right ?

**Comment by socram8888** [comment]
Nope. Which may be the reason it wasn't working for @turt2live.

**Comment by SpaceManiac** [comment]
Merged in b9ec84c8e7ff2b6a387967bd212dd662668c73a8.

**Pull request closed without merging**
