### PR TITLE
Redesign gh-pages branch

### PR DESCRIPTION
**Pull request by HenrySlawniak**
Just a super simple bootstrap and bootswatch site, live demo here: http://meggawatts.github.io/Glowstone/

### CODE REVIEW

**Comment by Aaron1011** [comment]
@meggawatts: This looks **really** nice!

**Comment by Postremus** [comment]
Little issue: If you are on the Downloads page and want to go to the
Api-Docs, you get a 404

2014-09-16 23:15 GMT+02:00 Aaron1011 notifications@github.com:

**Comment by ZephireNZ** [comment]
Your {{site.baseurl}} isn't working properly. Apparently you need to set the baseurl in the config file (http://jekyllrb.com/docs/github-pages/#project-page-url-structure)

**Comment by stuntguy3000** [comment]
Why did you remove  **target="_blank"**?

**Comment by HenrySlawniak** [comment]
atom.io did some weird things, fixed now

**Comment by SpaceManiac** [comment]
Looks pretty, I like it. It seems odd to me, though, to include the javadocs (which is compiled output) in the source control. Maybe link to greatman's javadoc hosting at http://build.greatmancode.com/job/Glowkit/javadoc/ instead?

**Comment by HenrySlawniak** [comment]
Didn't realize there were already javadocs for Glowkit somewhere. Diff is a lot more manageable now too. :D

**Comment by HenrySlawniak** [comment]
I feel like the three little blurbs could be simplified somehow. I would love to hear anyone's thoughts.

**Comment by SpaceManiac** [comment]
Maybe something along the lines of...

> Glowstone's code is completely original and licensed under the permissive MIT license. There is no reliance on decompiled code.
> 
> Simplicity breeds performance. Glowstone is built with both of these in mind, and offers benefits in situations where vanilla game features aren't needed.

Not final. I like the one about Bukkit.

**Comment by HenrySlawniak** [comment]
Been playing around with adding a little bit of color, that combined with the simplified blurbs seems to really make a difference.

**Comment by Nickforall** [comment]
That looks much better :+1: , but I like the leaf more for lightweight instead of the lightning.

**Comment by SpaceManiac** [comment]
A few comments:
- I don't think the "Minecraft" in the main header needs to be a link. There's a link later and IMO it looks nicer when the text style is uniform.
- The main header feels like it's got slightly too much vertical whitespace around it but this might just be me. Other parts of the page have this but not as bad.
- I know you just brought this from the old site but I don't think a Travis CI link is actually necessary. There's nothing there that's really useful to someone using Glowstone. Maybe link to the Github wiki instead?
- The downloads page should maybe have some intro text before the table so it doesn't feel as cramped, not sure what though.
- I'm not sure what's up with `... Lightstone. As well as Lightstone"s contributors.`

Other than that I really like it so far. Great work!

**Comment by SpaceManiac** [comment]
Another suggestion for the Downloads page: specify fixed column widths so that the headers don't rearrange themselves when the data is finished loading.

**Comment by HenrySlawniak** [comment]
Not entirely sure what merge conflicts there are. Any git magicians able to figure it out?

**Comment by SpaceManiac** [comment]
Probably just Github being annoyed about the fact it's `gh-pages` or something. If you consider this ready to merge, I'll take care of it.

**Comment by HenrySlawniak** [comment]
I'm happy with it, so if you're happy with it, go for it.

**Comment by SpaceManiac** [comment]
Merged in 52d79df143523fd60d08a56c4b05de17ce4a4a2d. Thanks!

**Pull request closed without merging**
