### PR TITLE
[WIP] Scoreboard 1.8

### PR DESCRIPTION
**Pull request by TuxCoding**
Update the scoreboard api for 1.8 clients. Based on the scoreboard branch from @SpaceManiac . 
The color feature from the scoreboard teams isn't complete implemented yet. In my opinion it needs some discussion what's the best way is to implement it.
So it's also not fully tested, but all possible values that will be sent are valid. (Chat color codes or -1 as reset)
All other implemented things are minor tested.

Changes:
- Add missing codecs and so missing features
- Add missing Override annoations
- Change a couple of integer values to VarInt
- Fix missing order of some packet values

Testing material:
- Source: https://gist.github.com/games647/8dd1fba7695c8553228a
- File: https://www.dropbox.com/s/j7jfs3yezknbrlp/ScoreboardTest.jar
- Just for testing propose.
- Example command: /test team xyz register

Related GlowKit ticket https://github.com/GlowstoneMC/GlowKit/pull/16
Related to #81 

ToDo: 
- Implement missing display slots.
- Make a complete rebase after review?

Questions:
Should [this](https://github.com/games647/Glowstone/blob/scoreboard1.8/src/main/java/net/glowstone/scoreboard/GlowTeam.java#L71) be done by a method, enum value or is this okay?
[Enum, boolean or String](https://github.com/games647/Glowstone/blob/scoreboard1.8/src/main/java/net/glowstone/scoreboard/GlowObjective.java#L111)? (It's currently implemented as enum on vanilla servers, so they may add more)
Should update packets only be sent on changes?

### CODE REVIEW

**Comment by Aaron1011** [comment]
@games647: Aww, I thought no one else was working on this :). I claimed it on Trello, and started working on it here: https://github.com/Aaron1011/Glowstone/tree/scoreboard.

I've done (pretty much) the same thing as you, but I'm also working on serialization. Currently, I've written (almost) all the code for reading the scoreboard NBT file, and haven't done the writing code yet.

Do you want to merge our branches somehow?

**Comment by TuxCoding** [comment]
@Aaron1011 Why not. There are just some conflicts or do you mean just the serialization part? 

And sorry didn't know that working on it too.

**Comment by Aaron1011** [comment]
@games647: Probably just the serialization part.

**Comment by stuntguy3000** [comment]
@games647 @SpaceManiac  Not sure if this has been mentioned/been fixed, however this is still worth to mention.

Currently Score#setScore doesn't work if the value is 0. The solution is to set it to a value that isn't 0, and then re-set it to 0. Im not sure if this is a Bukkit bug, but it exists none the less.

**Comment by TuxCoding** [comment]
@stuntguy3000 I guess the Bug doesn't exist in Glowstone, because it sends a packet on every setScore values, however it was changed or not. 

Should a packet be only send on change? I think it would be better. 

EDIT: Tested. Does actually work with setScore(0) without your workaround.

**Comment by daboross** [comment]
@stuntguy3000 https://github.com/stuntguy3000 IIRC, 0 not working in
setScore is a Minecraft client bug.

**Comment by stuntguy3000** [comment]
@daboross Damn, ok.

**Comment by stuntguy3000** [comment]
Do you think Glowstone should build in a workaround for this?

**Comment by daboross** [comment]
I think it is intended in the minecraft client that scores set to 0 shouldn't show. It might be confusing if it works differently in Glowstone than in other servers/APIs

**Comment by SpaceManiac** [comment]
I wouldn't worry about `setScore(0)` not working, as it currently is is probably fine.

> Should [this](https://github.com/games647/Glowstone/blob/scoreboard1.8/src/main/java/net/glowstone/scoreboard/GlowTeam.java#L71) be done by a method, enum value or is this okay?

It might make sense to make the name a value on the enum,

> [Enum, boolean or String](https://github.com/games647/Glowstone/blob/scoreboard1.8/src/main/java/net/glowstone/scoreboard/GlowObjective.java#L111)? (It's currently implemented as enum on vanilla servers, so they may add more)

I think having RenderType as an enum is fine for now.

> Should update packets only be sent on changes? 

Eh, doesn't really matter either way. This is a pretty minor optimization.

> Implement missing display slots.

I'm curious, what are the new display slots?

> Make a complete rebase after review?

I can take care of this during merging.

**Comment by SonarBeserk** [comment]
The client scoreboard ignores 0 unless you set it to something else like -1 first then set it to 0 so i would say leave it as is. It is still perfectly possible to make it show.

**Comment by gdude2002** [comment]
Just to confirm - with the `scoreboard` Glowkit branch, this **does not build**. http://bamboo.gserv.me/browse/GLOW-SRV-PR331-47

**Comment by turt2live** [comment]
@games647 This is looking pretty inactive code-wise. If this is complete, please remove "WIP" from the title to have it reviewed.

If this is still a work in progress, please comment back stating so. 

Thanks!

(PS: Remember to limit your scope. No need to implement all of scoreboards just yet. This PR looks pretty hefty in the size department)

**Comment by TuxCoding** [comment]
@turt2live I think @Aaron1011 pr would be better.

**Comment by dequis** [comment]
Yeah, rip.

Thanks for your time anyway!

**Pull request closed without merging**
