### PR TITLE
Remove org.bouncycastle libraries to reduce filesize significantly.

### PR DESCRIPTION
**Pull request by OverCaste**
They are unnecessary, as the javax libraries are faster and included in JDK implementations.

### CODE REVIEW

**Comment by OverCaste** [comment]
Got ahead of myself there fixing the last bug. Will revert gradle and re-open.

**Comment by SpaceManiac** [comment]
Think you could avoid rearranging imports too much? I know they're not especially well-organized at this point but it'd be nice not to make it worse until I decide on something better. If you want I can export my IDEA profile or something.

**Comment by OverCaste** [comment]
I accidentally left import formats on for the project, it's already fixed, won't happen again.

**Comment by SpaceManiac** [comment]
Testing proved successful. Merged in 98b9bdbc980bc42148f559f49ab957fad4a57118. Thanks!

**Pull request closed without merging**
