### PR TITLE
Add Eclipse and IDEA plugins to build.gradle

### PR DESCRIPTION
**Pull request by jimmikaelkael**
This will provide a few tasks to gradle for building project files for both IDE.
Those who wish to import an Eclipse project will do:
./gradlew eclipse
Those who wish to import an IDEA project will do:
./gradlew idea

### CODE REVIEW

**Comment by jimmikaelkael** [comment]
I added a 2nd commit as it's required that the project name match directory name so that it can be imported directly as a gradle project into Eclipse.

Let me know if you want me to squash this 2nd commit.

**Comment by SpaceManiac** [comment]
Merged in ed97e6810dee31d32b925522a8e0fcb03f1d1d3b.

**Comment by SpaceManiac** [comment]
Turns out that second commit is trouble - it changes all the file paths from 'glowstone' to 'Glowstone' as well. I think I'd prefer to see a workaround for loading things in Eclipse or a change which keeps the artifact names lowercase.

**Comment by jimmikaelkael** [comment]
I'm sorry for that, an alternate way to do this is to simply set an eclipse project name.

See PR #352

**Pull request closed without merging**
