### PR TITLE
Player Takes Void Damage

### PR DESCRIPTION
**Pull request by jaredStef**
When a player is deep in the void aka y axis is less than or equal to -64 the player takes 4 damage.

### CODE REVIEW

**Comment by turt2live** [comment]
`PRHOLD: Cacti hugging - contains additional required code`

**Comment by jaredStef** [comment]
I won't submit a PR for suffocation yet either and hmm my build failed. Let me look at the checkStyle

**Comment by dequis** [comment]
How does this depend on the [hugs PR](https://github.com/GlowstoneMC/Glowstone/pull/550)?

Also this seems like it would be nice to test timing of damage. From the mc wiki:

> Falling into the Void past Y=-64 causes the player's health to be depleted by about 4 (:heart::heart:) every half second, leading to the player's death in around 2.5 seconds. Armor does not protect you from dying in the Void, and death always occurs at Y=-199.10

**Comment by turt2live** [comment]
It will not work without the boiler plate code asked in the hugs PR.

sent from mobile

**Comment by dequis** [comment]
What boiler plate code? I see it adds canTakeDamage and isTouchingMaterial, neither of which are used or needed here

Although it does duplicate the `noDamageTicks = maxNoDamageTicks` line, but.. that's no reason to put it on hold.

**Comment by turt2live** [comment]
Exactly: it doesn't make use of them. It should make use of them for the
sake of consistency throughout the code.

sent from mobile

**Comment by dequis** [comment]
This doesn't need to be on hold anymore

**Comment by SpaceManiac** [comment]
Merged manually in 80ee09c652579da034f576b3eda89864dd4a6a1a. Thanks!

**Pull request closed without merging**
