### PR TITLE
Print out bound port

### PR DESCRIPTION
**Pull request by Aaron1011**
Currently, if `port` is set to `0` in the config, there's no way to determine the port that the server actually gets bound to.

This PR prints out the port that was bound t, and updates `getPort` to return the port actually bound if, if `0` was specified.

### CODE REVIEW

**Comment by Aaron1011** [comment]
This resolves issue https://github.com/GlowstoneMC/Glowstone/issues/571

**Comment by turt2live** [comment]
I don't think this needs a variable to be stored 0.01% of the time it will be used. Just pull the value from the bound socket.

**Comment by Aaron1011** [comment]
Then, I'd just be storing the channel or socket instead. It's not accessible from the main server outside `bind()`

**Comment by turt2live** [comment]
Then the variable should always be used

**Comment by SpaceManiac** [comment]
Merged in 1311a2a3330e60f9e4da56de4b160fc8b98d4e6f.

**Pull request closed without merging**
