### PR TITLE
Writing world data and minecraft.net name authentication

### PR DESCRIPTION
**Pull request by zml2008**
This adds reading of a world's level.dat and writing to a world's region file. Lighting is not saved correctly due to the lack of a proper lighting system. This also adds authentication with minecraft.net, using the same online-mode config option as the vanilla server.

### CODE REVIEW

**Comment by zml2008** [comment]
Will conflict with pull request #17 which adds basic BlockProperties checks. Mine check more though.

**Comment by zml2008** [comment]
Splitting the stuff here that's working well into smaller pullrequests

**Comment by zhuowei** [comment]
Is the BlockProperties drops going to be separated into another pull request?

**Comment by zml2008** [comment]
Space said he wanted to do this a bit differently, so I'm waiting on him

**Comment by zhuowei** [comment]
And is the world savings code going to be put into a separate pull request as well?

**Comment by zml2008** [comment]
yes. I want to get the saves to be compatible with vanilla and add loading
and saving of blockstates before I pullreq.

**Pull request closed without merging**
