### PR TITLE
Fixes for the changes in bukkit, a ban system + api, and a few more events called

### PR DESCRIPTION
**Pull request by zml2008**
PlayerPreLoginEvent, PlayerLoginEvent, and PlayerTeleportEvent were added

### CODE REVIEW

**Comment by zml2008** [comment]
So it looks like the permissions I added for vanilla commands aren't working properly ingame (even default true). The permissions act as expected in the console though. Dunno what's causing this though.

**Comment by zhuowei** [comment]
Bukkit re-implemented all of the standard commands recently ( bukkit/bukkit@0914132467dd338fa2094640deb3afcb2b7c03e5 ); maybe it's conflicting with our version?

**Comment by zml2008** [comment]
This includes standard command support, so stuff should work fine.

**Comment by zml2008** [comment]
Fixed the permissions problem. loadPlugins clears all the registered permissions and their defaults with pluginManager.clearPlugins(), so I changed the order of registration.

**Comment by SpaceManiac** [comment]
The first five commits are now in master and the last two are now in mc-1.8. Thanks!

**Pull request closed without merging**
