### PR TITLE
Switched to GPLv3 license.

### PR DESCRIPTION
**Pull request by JeromSar**
See issue #147 For details.

### CODE REVIEW

**Comment by Ribesg** [comment]
Need acceptance by the following people before being merged:
- [ ] @SpaceManiac 
- [ ] @grahamedgecombe 
- [ ] @zml2008 
- [x] @zhuowei 
- [ ] @desmin88 
- [x] @Grinch 
- [x] @akrieger 
- [ ] @hef 
- [x] @OverCaste 
- [ ] @lukespragg 
- [ ] @wtfaremyinitials 
- [ ] @kitskub 
- [ ] @deathcap 
- [ ] @warriordog 
- [ ] @UltraFTW 
- [ ] @ewized 

Just answer with "I agree" (or moar) here.

**Comment by Grinch** [comment]
I hereby agree that all submitted code by myself, Steven Downer (aka @Grinch) to Glowstone is allowed to be relicensed to GPLv3.

**Comment by gdude2002** [comment]
> Just answer with "I agree" (or moar) here.

Moar!

**Comment by JeromSar** [comment]
The MIT license allows sub-licensing and is thus fully compatible with the GPLv3 license. No "consent" is required.

**Comment by gdude2002** [comment]
I believe that we should still get consent to avoid kicking the contributors in the dick, so to speak, and doing something they haven't had a say in.

That said, if this takes more than a few days, we might have to do it. But it's not our project to do that to, let's wait for @SpaceManiac

**Comment by OverCaste** [comment]
My patches are licensed under the "don't bother me unless it's for a good reason" license, which is fully compatible with GPL.

Count me in.

**Comment by wtfaremyinitials** [comment]
@OverCaste is that a real license? I might need to start using that.—

**Comment by basicer** [comment]
Please see http://www.gnu.org/licenses/gpl-faq.html#LinkingWithGPL

All that is required here is to make the binary JAR that is distributed on glowstone,net GPL.

**Comment by dumptruckman** [comment]
I agree with @basicer 

This would allow a much friendlier licence (such as MIT) to be used for the source code.  (This means the PR needs to be fixed!)

**Comment by dumptruckman** [comment]
Okay, apparently not so simple.
["Subclassing is creating a derivative work. Therefore, the terms of the GPL affect the whole program where you create a subclass of a GPL'ed class."](http://www.gnu.org/licenses/gpl-faq.html#OOPLang)

**Comment by JeromSar** [comment]
@dumptruckman is correct, GlowStone must be licensed under GPLv3. However, no consent is required because the MIT license (current license) explicitly permits sub-licensing.

**Comment by basicer** [comment]
@dumptruckman - Sub-classing still happens at build time, the "whole program" that is affected is the resulting JAR.

**Comment by dumptruckman** [comment]
Changing to GPLv3 will make the project legal with no questions asked and doesn't appear to affect anything else.  The only case would be any further mods to Glowstone would be required to be GPLv3... like if Glowstone had its own spigot kinda thing.  Plugins are not affected by this change as they depend on Bukkit and their license issues appear to be an unrelated issue.

**Comment by zhuowei** [comment]
I agree.

**Comment by olliestanley** [comment]
Seems like changing to GPL is the best way, especially if it doesn't require consent.

**Comment by basicer** [comment]
The fact that it doesn't require consent is a large part of the reason why nothing needs to be done.

Also, if people really want to make usage under the GPL explicit, why not instead move to a dual licensing system of MIT/GPL instead of removing the MIT license.  Removing the MIT license will removing freedoms people had to deal with the code that they previously had.

For example, NibbleArray is a pretty cool class.  Maybe I would like to use that in some unrelated Java project in the future.  Switching to the GPL license would mean I couldn't reuse that bit of code, even though it is totally unrelated to Bukkit.

For example, jQuery use to license their code under combination MIT/GPL license.  (They  later switched to using just the MIT license, because as I have been saying, having both is redundent http://blog.jquery.com/2012/09/10/jquery-licensing-changes/)

**Comment by JeromSar** [comment]
@basicer The terms of GPL prevent dual-licencing. The original MIT license is not legally valid due to Bukkit being licensed under GPL.

**Comment by basicer** [comment]
I'm not sure what your legal basis for that is.  Can you explain?  To me it seems unlikely a project as popular as jQuery would have had an "invalid license" for several years.

**Comment by dumptruckman** [comment]
@basicer Craftbukkit was a popular project and had an invalid license for years. ;)

**Comment by JeromSar** [comment]
@basicer The MIT license is not an invalid license. However, because this project includes Bukkt (GPL), GlowStone is legally required to be licensed under GPL too.

jQuery on the other hand completely owns their own code and thus may change licence whenever they like.

**Comment by basicer** [comment]
http://www.gnu.org/licenses/gpl-faq.html#LinkingWithGPL says that a work (GlowStone) that is combined with a GPL Library (Bukkit) can be licensed under a GPL compatible license (MIT).  The resulting program (the JAR file) would then be licensed under the GPL.

That FAQ entry describes exactly what is happening here.  The glowstone sorce sitting alone in a GIT repository is not a derivative work of Bukkit.  When we compile and link GlowStone against Bukkit, we are creating a derivative work.

**Comment by dumptruckman** [comment]
http://www.gnu.org/licenses/gpl-faq.html#OOPLang and http://www.gnu.org/licenses/gpl-faq.html#LinkingWithGPL seem to contradict each other for our specific case....

**Comment by basicer** [comment]
Notice in that section it refers to the "whole program".  This is the JAR file.

**Comment by akrieger** [comment]
I agree.

**Comment by dumptruckman** [comment]
Hmm yeah, could be the case.  Someone should reach out to FSF and see if they can help.

**Comment by SpaceManiac** [comment]
Closing this in favor of applying the GPL to only the distribution, not the source code, as discussed on IRC and elsewhere.

**Pull request closed without merging**
