### PR TITLE
Leather armour meta

### PR DESCRIPTION
**Pull request by ZephireNZ**
This adds in leather armour meta, allowing for plugins to change the colour of leather armour.

Has been tested, and seems to work well.

---

_Edited by turt2live_

**Related Links:**
- Ticket: #77

### CODE REVIEW

**Comment by turt2live** [comment]
I almost want to just push this myself because you spelled `armour` correctly in the description :+1: 

Edit: AND IN THE TITLE. THANK YOU. :heart:

**Comment by dequis** [comment]
inb4 @turt2bot decides it needs retesting

**Comment by dequis** [comment]
Heh, I think github fucked up the DST switch, says 6:56 GMT-3 for my first comment about "ready to pull" and 6:01 GMT-3 for my second comment about "inb4 turt2bot". Time travel!

**Comment by dequis** [comment]
"ready to pull", and nobody cared about the checkstyle failures that result in those :x:

**Comment by ZephireNZ** [comment]
Dammit, that's my fault. I disable the check style to speed up builds. I'll
clean it up ASAP.

**Comment by turt2live** [comment]
The PR is auto formatted before pull.

sent from mobile

**Comment by dequis** [comment]
Referencing #77

**Comment by dequis** [comment]
Simple conflict in GlowItemFactory, keep both sides. [Branch](https://github.com/dequis/Glowstone/compare/pr-496). This one is actually your fault (skulls and banners)

**Comment by turt2live** [comment]
Confirmed operational with @dequis's branch, `pr-496`.

**Comment by ZephireNZ** [comment]
Awesome :)

**Comment by ZephireNZ** [comment]
My computer is currently a paperweight, so I can't add the merge here, best to use theirs.

**Comment by turt2live** [comment]
Paperweights are fun. And yes, I just nagged you on another PR of yours and read your paperweight story afterwards. 

Thanks though!

**Comment by SpaceManiac** [comment]
Merged in edbd3e0ecd47fe5554ddc59c7ff78402c088aafd.

**Pull request closed without merging**
