### PR TITLE
Replace Bukkit with Spigot-API

### PR DESCRIPTION
**Pull request by deathcap**

### CODE REVIEW

**Comment by ewized** [comment]
Why?

**Comment by EntityReborn** [comment]
What? No.

**Comment by lukespragg** [comment]
Replacing one zombified API for another doesn't really solve anything. As @SpaceManiac said, best to wait to see what happens once the dust settles and go from there. If anything, it'd be best to maintain a fork of Bukkit directly, and pull in any specific fixes from other forks if needed/wanted.

**Comment by SpaceManiac** [comment]
I'd need to see some pretty strong justification to accept this.

**Comment by EntityReborn** [comment]
And the current drama with the DMCA's doesn't count :)

**Comment by lukespragg** [comment]
It actually does @EntityReborn, as the fate of the APIs may change based on if they are updated by Mojang/Dinnerbone or not. So that's why it'd be best to wait and see what happens, and go from there. No sense jumping to a Bukkit fork or forking it directly until absolutely necessary.

**Comment by deathcap** [comment]
Alright I'll close this PR, seems its not the way to go.

**Pull request closed without merging**
