### PR TITLE
Added the mob spawning code from CraftBukkit

### PR DESCRIPTION
**Pull request by zhuowei**
Pig, Chicken, Cow and Sheep can be spawned; the rest are commented out until the respective classes are made.

### CODE REVIEW

**Comment by SpaceManiac** [comment]
My plan is to hold out on mob classes and associated spawning code until I have something meaningful to put inside them - I've been planning the mob AI infrastructure in my head and should put it on paper sometime.

**Comment by zhuowei** [comment]
What about other entities, such as boats?

**Comment by SpaceManiac** [comment]
Those will probably also get work done around the same time.

**Comment by akrieger** [comment]
Also I'm not sure what the licensing issues copying code can do. Ideally Glowstone would be completely separate from CB, being only an implementation of Bukkit. While it probably won't matter, copying the code over does break the clean-room reverse engineering principle which Glowstone would be following by just implementing Bukkit.

**Comment by rmichela** [comment]
CB is LGPL. Glowstone seems to be licensed under a public domain license. To legally incorporate CB code into Glowstone you will have to make the project GLP or LGPL, both of which are more restrictive than your current license.

**Comment by zhuowei** [comment]
Good point. I'll close this pull request then.
Also, the license is the MIT license, not public domain.

**Pull request closed without merging**
