### PR TITLE
Fix spectator mode

### PR DESCRIPTION
**Pull request by Aaron1011**
Thanks to @coelho for discovering that setting the gamemode in `UserListItemMessage` enables noclip.

This PR enabes noclip and flying when in spectator mode. Spectating entities still needs to be implemented.

### CODE REVIEW

**Comment by turt2live** [comment]
"fixes" is broad. What exactly does this do? Spectator mode is broken to oblivion right now.

**Comment by dequis** [comment]
Might be clearer with the description from the comments of #318:

> It is actually the UserListItemMessage which causes the player to noclip. At the moment Glowstone isn't updating the player's gamemode in the 1.8 user list when it is changed, and as such that produces this issue. Fixing it is as simple as adding this to the end of setGameMode

As for the actual effects of that, it enables noclip and flying.

**Comment by Aaron1011** [comment]
@turt2live: I've clarified the description.

**Comment by turt2live** [comment]
@Aaron1011 
- Spectator players are not semi-transparent heads
- Spectator players can be seen by non-spectator players

It would be appreciated to fix those alongside any others that were missed.

**Comment by SpaceManiac** [comment]
Merged in 060ff74eae7e8aa3dac1be841bc007b596f72d0d.

**Pull request closed without merging**
