### PR TITLE
Added sneaking support

### PR DESCRIPTION
**Pull request by zhuowei**
The sneaking support is based on lightstone's sneaking support.

### CODE REVIEW

**Comment by SpaceManiac** [comment]
Will look over this as soon as I get the chance. I need to double-check the way the public setSneaking is intended to work as the docs are unclear about whether it is intended to freeze the player in a sneaking state or set them that way until they sneak and unsneak again.

**Comment by SpaceManiac** [comment]
Double-checked - your implementation of setSneaking is correct. I'll look over this for cleanliness (it's got some complex stuff going on) when I get a chance.

**Comment by zhuowei** [comment]
Basically the list that stores mob metadata is moved to GlowLivingEntity and sneaking is done by setting the flag for it in the metadata.

**Comment by SpaceManiac** [comment]
Merged in f7e4463d430b2eee73f5c58421ee128073116bf5.

**Pull request closed without merging**
