### PR TITLE
Implement BlockContainer.getDrops()

### PR DESCRIPTION
**Pull request by dequis**
Drops the container block itself, and all the items from its inventory.

Fixes the weird looking item that chests dropped (was chest + data)

### CODE REVIEW

**Comment by dequis** [comment]
Screenshot of the weird-looking item:



This happened because the default implementation of BlockType.getDrops does the following:

```
return Arrays.asList(new ItemStack(block.getType(), 1, block.getData()));
```

My implementation removes the getData to return a pure chest block:

```
list.add(new ItemStack(block.getType(), 1));
```

And additionally includes the whole inventory as part of that list, so items are not lost.

**Comment by JeromSar** [comment]
Looks really good @dequis. You should probably warn when the expected block is not a `TEContainer`. :)

**Comment by dequis** [comment]
Is there any case in which the tile entity of the expected block is not a `TEContainer`?

As far as I know, since this is `BlockContainer`, its subclasses (such as `BlockChest`) create tile entities that subclass from `TEContainer` (such as `TEChest`)

**Comment by JeromSar** [comment]
@dequis Correct, but you can never be too sure. We do the same for `BlockType` classes. https://github.com/GlowstoneMC/Glowstone/blob/master/src/main/java/net/glowstone/block/blocktype/BlockDispenser.java#L34

**Comment by turt2live** [comment]
Sorry - bot fail :(

**Comment by turt2live** [comment]
Looks good!

**Comment by SpaceManiac** [comment]
Merged in d70a3e8133a94e1276f9f6478415327cc2e2a561.

**Comment by dequis** [comment]
:heart:

**Pull request closed without merging**
