### PR TITLE
Added Java 1.5 Override annotations where required

### PR DESCRIPTION
**Pull request by JeromSar**
This change adds the Override annotations where required and possible.

### CODE REVIEW

**Comment by coelho** [comment]
To be noted, in Java 1.5, you can not add Override annotations to implementations of\* interfaces.

**Comment by JeromSar** [comment]
@coelho Correct, this behaviour changed in Java 1.6. We however compile in Java 7 so this shouldn't be a problem.

**Comment by olliestanley** [comment]
I approve of this, I hate reading through code where there are some methods which are overriden and some which aren't but you can't tell which is which because there is no annotation.

**Comment by SpaceManiac** [comment]
I will double-check nothing got missed, merge this, then include it in the style guide when that gets written.

**Comment by JeromSar** [comment]
@SpaceManiac I set my compiler to fail compiling if Override annotations weren't present. Then I auto-fixed all missing annotations automatically. Gosh, NetBeans is awesome. :)

**Comment by SpaceManiac** [comment]
Fixed manually in a357d2c62661ac89910688e499e849f026c9e7dc. Thanks!

**Pull request closed without merging**
