### PR TITLE
Add note about Trello to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Aaron1011**

### CODE REVIEW

**Comment by TuxCoding** [comment]
:+1:

**Comment by turt2live** [comment]
Not everyone has access to Trello. It's a resource for more active contributors so that 5 people aren't all working on the same thing.

**Comment by greatman** [comment]
@turt2live The board is public so everybody have access to it. To modify you need to ask someone from board tho.

**Comment by turt2live** [comment]
@greatman Exactly :P

**Comment by Wild1145** [comment]
Could I suggest having some people here that are active within the issues / PR's who can just assign people to tasks. That way if a developer wants to work on something, they can post, be assigned to it, and you dont have to use third party tools / software.

Alternatively we could create a wiki page where people can follow a template to post what they are working on, that way again we dont use a third party site or something?

**Comment by turt2live** [comment]
There's nothing wrong with the using a third party site. GitHub isn't really designed for this kind of thing though, so I don't see that going well.

**Comment by Wild1145** [comment]
Github is alright for the smaller projects, where there are mostly just people who can self assign and such, but I think using third party software while isnt "bad" or a problem, just makes it that one step harder for people to contribute. if as much as possible could be done "In House" I think that would end up better in the long run for the project, especially when github has the tools to do this.

**Comment by turt2live** [comment]
Glowstone is rapidly getting larger though. Many of the tools on GitHub aren't helpful any more to us... 

Although it does make it harder to contribute, I don't think that this should be a requirement anyways. Trello is really only used so 5 people don't work on the same code (currently), but new contributors can always ask in IRC before diving into the project. If someone is not working on the idea the contributor mentions, someone in IRC can add a card and that contributor can open a WIP PR.

And even if they don't check before contributing it's not the end of the world. They may have written something that is more appropriate or correct for the problem being solved. Then again, they could have written something worse, but those are dealt with anyways.

**Comment by Postremus** [comment]
Or they could maybe came up with a better way to implement the feature.

2014-09-21 22:38 GMT+02:00 Travis Ralston notifications@github.com:

**Comment by Wild1145** [comment]
Just as an idea, if someone is working on a issue, they could comment on it, something like "Currently working on this issue" or something to that extent, as people will need to read the issues before contributing anyway, I know its not the most ideal way of doing it, but unless Glowstone gets a separate issue tracking system that has a few more advanced features to what the Github one does, it may be a option for those who dont necessarily want to check Trello or anything else every time.

**Comment by turt2live** [comment]
Commenting on issues would be best, in addition to updating trello as required. There's nothing wrong with popping in IRC and asking though.

As long as it's clear that SOMEONE is working on something then we won't have 20 PRs that do the same thing.

**Comment by Wild1145** [comment]
Yeah... I cant see as 20 PR's trying to do the exact same thing will ever be amazingly helpful. But to be honest, doing all three of the mentioned things would be useful, even if you dont post it on Trello, someone else can for you then maybe?

**Comment by turt2live** [comment]
That was my suggestion :P

**Comment by Wild1145** [comment]
Im not sure how trello works, but is there anything stopping other people updating it on others behalf's? or would that not really work?

**Comment by turt2live** [comment]
There's nothing really stopping it beyond human capabilities and intelligence.

**Comment by Wild1145** [comment]
Okay, I didnt know if there were any form of practical reasons for it or not.

**Comment by SpaceManiac** [comment]
Merged in 7facfec4453fa702b9124c0d89ae45428b45f51e.

**Pull request closed without merging**
