### PR TITLE
Added Hay, Log, Quartz, Ladder, Vine

### PR DESCRIPTION
**Pull request by ZachBora**
Added 3 more block handling
#119

### CODE REVIEW

**Comment by Wild1145** [comment]
Just as a nice tip for future commits, if you commit and include "Resolves #<issue number>" when pulled in it will mark the issue as closed instantly. Its just a nice little thing I thought you might want to know for future pulls ;)

**Comment by ZachBora** [comment]
@Wild1145 Except it doesn't fully resolve it

**Comment by Wild1145** [comment]
@ZachBora Fair enough, just thought I'd say in case you didn't realize.

**Comment by SpaceManiac** [comment]
Hay and quartz merged in 61914c1. I ran into a little bit of wonkyness with ladders and vines, I'll merge those when I've figured them out.

**Comment by ZachBora** [comment]
Weird I didn't have issues with ladders and vines. Maybe I forgot cases.

**Comment by SpaceManiac** [comment]
PR closed itself because I deleted the branch, feel free to create a new one with Ladders and Vines against master.

**Comment by ZachBora** [comment]
Ok I think I know what the issue was.

**Pull request closed without merging**
