### PR TITLE
Toggle between normal and inverted daylight sensor on interact

### PR DESCRIPTION
**Pull request by Aaron1011**

### CODE REVIEW

**Comment by Tonodus** [comment]
Why do you have two classes? Better use a boolean to detect the inverted state. Btw this isn't that useful at the moment.

**Comment by Aaron1011** [comment]
@Tonodus: I thought about that, but considering they're two separate block types (not data values of the same block), I thought they should have their own classes.

I know it doesn't do anything except switch them, but it's a start for when redstone is (eventually) implemented.

**Comment by Tonodus** [comment]
The daylight detection should be nearly the same, expect of an '!' at the end for the inverted one, shouldn't it? That would be much cleaner in one class.
Also there are many classes that cover more than one Material.

**Comment by turt2live** [comment]
A boolean state is better in general. Just because they are different in a data format does not mean they have to be represented by different objects. The single object can figure out which logical type it is based upon it's data (or whatever) instead of the plugin/calling code.

**Comment by Aaron1011** [comment]
I've removed the `BlockDaylightDetectorInverted` class.

**Comment by dequis** [comment]
One checkstyle failure

**Comment by Aaron1011** [comment]
@dequis: Thanks, fixed it.

**Comment by SpaceManiac** [comment]
Merged in a8d6eefa1a53017a59077ce41e07f427dac4e606.

**Pull request closed without merging**
