### PR TITLE
[WIP] More network unit tests

### PR DESCRIPTION
**Pull request by greatman**
Signed-off-by: William Lebel lebelwilliam@gmail.com

### CODE REVIEW

**Comment by ghost** [comment]
I dont think the way glowstone going is right way to test network. I would suggest use https://github.com/Steveice10/MCProtocolLib.

**Comment by greatman** [comment]
Eh. Networking is already all done in Glowstone. It use flow-networking as backend. This is mostly to prevent stupid errors in the code. See https://github.com/GlowstoneMC/Glowstone/pull/281

**Comment by ghost** [comment]
The goal of unit test is be sure that all works like it should. This protocol test own protocol. I suggest write packet from mcprotocol and read from glowstone and other way round. For my server implementation i also wrote bot that doing basic staff(join, dig, moving) and gurantee that all works.

**Comment by ghost** [comment]
Example from my server implementation: 

``` java
 @Test
    public void testHandshake() throws IOException {
        ByteBuf buffer = Unpooled.buffer();

        // MCProtocolLib - Write
        ByteBufNetOutput out = new ByteBufNetOutput(buffer);
        HandshakePacket packetOut = new HandshakePacket(ProtocolConstants.PROTOCOL_VERSION,
                "localhost", 25565, HandshakeIntent.LOGIN);
        packetOut.write(out);

        // My server implementation - Read
        PacketBuffer in = new PacketBuffer(buffer);
        PacketHandshake packetIn = new PacketHandshake();
        packetIn.read(in);

        // Now getting data from read packet and testing for equals
        assertEquals(ServerInfo.PROTOCOL, packetIn.getProtocol());
        assertEquals("localhost", packetIn.getIp());
        assertEquals(25565, packetIn.getPort());
        assertEquals(PacketState.LOGIN, packetIn.getState());
        assertFalse(buffer.isReadable());
    }
```

Also maybe need with mocks test packet execute part?

**Comment by greatman** [comment]
Problem is, what if the other custom implementation is the one being wrong?

**Comment by gdude2002** [comment]
Who tests the other impl?

Dammit @greatman, ninja'd me again

EDIT: Maybe there's some way of using the MCP to do this. It's the reference implementation, after all.

**Comment by ghost** [comment]
@greatman Fix it and send pull requests? This is not really problem. At least you will be sure that protocol works fine with new version. 

@gdude2002 it's just a tool to test glowstone protocol. Edit: Very overhelming and not updating so fast

**Comment by SpaceManiac** [comment]
I feel the current tests are reasonable as checks for the round-trip encode/decode. It might be worthwhile to test the actual encoded data in some way, such as against another implementation or against encoded bytes in the tests, but I'm not sure if this can be done simply. I'm open to suggestions.

I think testing the handlers isn't as important. Some of them, such as WindowClickHandler (which is incredibly complicated), have portions tested in

**Comment by ghost** [comment]
Just showing how far i gone http://pastebin.com/D4J77inY

**Comment by turt2live** [comment]
@greatman Last activity on this was **October 13th** (**38** days ago), any updates on how this is going?

**Comment by turt2live** [comment]
@greatman I seem to recall some kind of response to my last ping on IRC, but I can't remember what it was... So here's a complementary reminder seeing as it's been over a month since my last request.

There has been no activity on this pull request for almost a month now. Is this still being worked on or is there some circumstance that has interfered? Please respond as soon as possible, thanks!

**Comment by turt2live** [comment]
I'm closing this due to severe inactivity. If anyone, including the author ( @greatman ), would like to continue this work, please open a new pull request. 

Thanks for the contribution though!

**Pull request closed without merging**
