### PR TITLE
Add warning for turning off online-mode

### PR DESCRIPTION
**Pull request by wtfaremyinitials**
Fix for #93.

### CODE REVIEW

**Comment by ewized** [comment]
If you want the issue to be closed you need to push `fixes #`  right next to each other.

**Comment by wtfaremyinitials** [comment]
Fix #93

**Comment by wtfaremyinitials** [comment]
Fixes #93.

**Comment by SpaceManiac** [comment]
Merged with formatting changes in f250bfbab9b287e5885f0c18fbaa6050fbe6167b - thanks!

**Pull request closed without merging**
