### PR TITLE
Add space to console input

### PR DESCRIPTION
**Pull request by maxov**
This is a simple change with a space at the end of the console reader. This is standard Bukkit and Minecraft behavior, and changes the session from this:

```
>whitelist off
whitelist off
11:55:52 [INFO] CONSOLE: Turned off white-listing
>toggledownfall
toggledownfall
11:55:55 [INFO] CONSOLE: Toggling downfall on for world 'world'
```

to this:

```
> whitelist off
whitelist off
11:55:52 [INFO] CONSOLE: Turned off white-listing
> toggledownfall
toggledownfall
11:55:55 [INFO] CONSOLE: Toggling downfall on for world 'world'
```

Also first actual PR, and fittingly so for something so trivial.

**EDIT**: SpaceManiac, dequis, and I have tested and confirmed that this is in fact _not_ standard behavior in CraftBukkit, Spigot, or the Minecraft server. Still, it does increase readability.

### CODE REVIEW

**Comment by dequis** [comment]
This is too complex for a single PR, can you try splitting it in several parts for easier reviews?

**Comment by turt2live** [comment]
This isn't suitable as a pull request. Thank you for your contribution.

**Comment by dequis** [comment]
wait really

**Comment by turt2live** [comment]
For those that don't stalk IRC chat, here's why this was closed (in more detail):

_I will be using this PR as an example, do not take it personally @gratimax_

Pull requests that are small, such as this one, are not large enough to warrant a full discussion and review cycle. Smaller PRs are also not fit for the description of "contributor". By having yourself listed as a contributor to the project for a formatting change, we are implying that you have made a serious effort to improve the project in some way. 

As for what qualifies as a small PR, that depends. The handler (currently only myself and @SpaceManiac, technically) generally decides based upon common sense. Some examples include JavaDoc changes, formatting, small features (such as adding a space), and more. If you are uncertain if your potential pull request is "large enough", feel free to ping me on IRC (the information is on the repository's readme). 

When small PRs are closed it is not intended to be anything personal. It doesn't even mean that your change is rejected. It just means that the PR is not large enough to warrant the use of the PR system. Instead we would prefer you hop on IRC and pitch your minor change to the people in the room. Ideally you would want @SpaceManiac present so he can enact (or not) your idea. As an example, this PR would go down something like this in IRC (I apologize to those who are about to be victims of my example):

```
<gratimax> Hey SpaceManiac, what do you think about adding a space between the '>' and the command? 
<dx> I like it! 
<SpaceManiac> Sounds like a good idea, let me commit that.
<GlowstoneBot> SpaceManiac has pushed 1 new commit to master
```

or it could go down like this...

```
<gratimax> Hey SpaceManiac, what do you think about adding a space between the '>' and the command? 
<SpaceManiac> I'm not sure if our users would appreciate that as it changes what they're used to in CraftBukkit. Thanks for the suggestion though!
```

As you may have noticed, I've forwarded simple things like this to SpaceManiac instead of myself. I'll personally let you know if your PR is too small (or too large in some cases) and forward you to SpaceManiac as needed while SpaceManiac will help determine whether or not the small feature needs to be included in the repository. 

I hope this makes sense. If it doesn't, or if more clarification is needed, please respond back here or hop on IRC.

Thanks!

**Pull request closed without merging**
