### PR TITLE
Center website on screens with enough space

### PR DESCRIPTION
**Pull request by Ribesg**

### CODE REVIEW

**Comment by turt2live** [comment]
It looks good as-is though :(

**Comment by SpaceManiac** [comment]
Does not work on Firefox as far as I can tell.

**Comment by turt2live** [comment]
May have to clear your cache (CTRL+F5 to refresh & clear cache)

**Comment by Ribesg** [comment]
Sorry, forgot that x)

The intended result happens with the added media query.

**Comment by turt2live** [comment]
Sorry - bot fail :(

**Comment by SpaceManiac** [comment]
I appreciate the effort, but I'm closing this in favor of #291.

**Pull request closed without merging**
