### PR TITLE
Add a script that fetches glowkit PRs for travis

### PR DESCRIPTION
**Pull request by dequis**
Also reorganize .travis.yml slightly (actual build stuff goes in the script step, preparations go in the install step)

The script uses the github API to fetch the pull request body (which is needed to find the relevant PR links).

Since the github api has very strict rate limits for unauthenticated users, I've included an [oauth personal access token](https://github.com/settings/tokens/new) with scope for public repositories only. This means that compared to unauthenticated access, it's only useful to bypass the rate limit

I'd still recommend using the travis encryption features for the token, just in case. I'd like to revoke mine as soon as testing is done.

Also note that using the encryption features means the script won't work in other repos, but this isn't an issue since it's also hardcoded to fetch PRs from Glowstone/Glowstone and Glowstone/Glowkit.

Did some testing for it [here](https://travis-ci.org/dequis/Glowstone/pull_requests) and [here](https://travis-ci.org/dequis/Glowstone/builds). The commit labeled "TESTING SHIT" (now reverted) calls the script three times with hardcoded ids instead of `$TRAVIS_PULL_REQUEST`. These PRs are:
- #374 - no glowkit PRs required
- #402 - two PRs ~~required~~ mentioned, ignored by the script. The author of that PR said they aren't needed.
- #413 - one PR required, detected correctly by the script and built successfully, but in the end the build fails because the glowstone side doesn't have the required changes. For the purposes of my script, this means it works.

### CODE REVIEW

**Comment by turt2live** [comment]
There is one failing case: `GlowstoneMC/Glowkit#000`. That format is used and is not parsed.

**Comment by dequis** [comment]
Added the requested changes, plus checking if the linked PRs are issues/closed PRs.

If you wish to test the parsing of PR body without submitting actual PRs, comment out the `pr_body=...` line and use something like this instead:

```
pr_body='GlowstoneMC/Glowkit#30 GlowstoneMC/Glowkit#25 GlowstoneMC/Glowkit#12 GlowstoneMC/Glowkit#26 GlowstoneMC/Glowkit#0'
```

**Comment by turt2live** [comment]
Leaving this to @SpaceManiac to decide whether or not it should be included

**Comment by dequis** [comment]
Added another commit that should make it easier to switch to encrypted tokens on the travis side - just comment out (or remove) the line that sets `GITHUB_ACCESS_TOKEN`, and provide it externally.

The script can continue to work with the access token removed when using it outside of travis, but the rate limit of 60 requests per hour makes it useless for anything else.

**Comment by SpaceManiac** [comment]
A couple of questions:
- Would it work to move `sudo apt-get install jq` the script so it isn't installed on non-PR builds?
- (Somewhat unrelated, but while we're on the Travis script) I understand using the wrapper is the recommended way to do things, but downloading Gradle now takes up over half the build. Is it reasonable to use the system `gradle` instead?

**Comment by dequis** [comment]
> Would it work to move sudo apt-get install jq the script so it isn't installed on non-PR builds?

I wanted to keep the script as travis-agnostic as possible, but i'll add some real PR checks to the install script.

> Is it reasonable to use the system gradle instead?

Yeah, I think so. Will test.

**Comment by dequis** [comment]
System gradle works: https://travis-ci.org/dequis/Glowstone/builds/38678302 (the build ends as a failure because it's using outdated glowstone with a newer glowkit, but meh)

Also seems that this reduces the build time by 40 seconds \o/

**Comment by dequis** [comment]
Dammit @turt2live.

_pokes @SpaceManiac_

**Comment by dequis** [comment]
1 min 38 sec (this build)
vs
2 min 14 sec (previous successful build)

:D

**Comment by SpaceManiac** [comment]
Merged in 25dc62aa229709018ff821bb9fb9c83c318ae667.

**Comment by ZephireNZ** [comment]
Cannot merge. GG

**Comment by dequis** [comment]
good job @turt2bot

**Pull request closed without merging**
