### PR TITLE
Version number now OVER 9000!

### PR DESCRIPTION
**Pull request by zhuowei**
This should "fix" issue #26.
@winsock, I hope you are happy.
The version number reported by the new and more powerful Glowstone: 
`This server is running Glowstone version 9001.git-Glowstone-0.0.0-133-g44093b6`

### CODE REVIEW

**Comment by winsock** [comment]
I support this :D

**Comment by zhuowei** [comment]
Maybe I should future-proof it by changing the version number to 9002? :)

**Comment by winsock** [comment]
That might result in a StackOverflowException!!!!!

**Comment by zhuowei** [comment]
Let's make sure we get the stack to overflow.

`public String getVersion(){
    return "OVER 9" + thousand();
}
private String thousand(){
    return ",000" + thousand();
}`

**Pull request closed without merging**
