### PR TITLE
Drop attached blocks when the block it's attached to is destroyed by a player.

### PR DESCRIPTION
**Pull request by jimmikaelkael**
OK, I know the code is currently awful. I'd like to have some point of views as I'm not sure the proper way to handle this would be in BlockType.

### CODE REVIEW

**Comment by dequis** [comment]
Isn't this essentially the same as BlockNeedsAttached from #249?

**Comment by jimmikaelkael** [comment]
The same ? No judging by the length #249 is far more complete :)
Otherwise you're true @dequis, that's it.

Closing this, sorry for the trouble.

**Comment by ZephireNZ** [comment]
Good lord that is a copy-paste mess. You'd be better off creating an array/list of the directions, and then iterating over that.

**Comment by jimmikaelkael** [comment]
Did you read my 1st comment ? No it seems...
Anyway this is closed in favor of Tonodus's Block Physics PR.

**Pull request closed without merging**
