### PR TITLE
Fix disconnect when sending empty chunks

### PR DESCRIPTION
**Pull request by coelho**
When we send an empty chunk, we are expected to send the biome data. As of the current build of Glowstone, we do not do this, and it causes the client to disconnect. This PR fixes that issue.

### CODE REVIEW

**Comment by turt2live** [comment]
What disconnect?

**Comment by coelho** [comment]
If you are in a world with empty chunks (ie. the end) then you will be disconnected due to a Netty DecoderException as it tries to read the biomes. #245 is related, but it was incorrectly closed.

**Comment by turt2live** [comment]
Does this touch or even look at #136 or #127 ? #245 was closed. If no ticket currently exists, can you create one please?

**Comment by SpaceManiac** [comment]
Dabo on IRC independently confirmed the problem's existence and that it is fixed by this PR.

**Comment by daboross** [comment]
I reproduced this when testing SkyWars (download http://ci.daboross.net/d/SkyWarsParent_SkyWars_MainBuild/SkyWars.jar). The plugin uses a generator which returns empty chunks, then populates with a few islands where the players stand.

A screenshot of the error I was getting can be found at http://qx.lc/wQQ9. The error no longer exists with this PR.

**Comment by turt2live** [comment]
Looks as though it's working. Looks like a solid implementation as well. Ready for pulling :)

**Comment by SpaceManiac** [comment]
Merged in 3641cf44af60cd504c32aabd2daef6ea9ca7bfd7.

**Comment by xvento** [comment]
image

I have this problem please help

**Comment by turt2live** [comment]
@xvento Please open a new ticket with more information or consult our forums. Thanks!

**Pull request closed without merging**
