### PR TITLE
Add some vanilla structures

### PR DESCRIPTION
**Pull request by jimmikaelkael**
This PR will add some vanilla structures.

Work done:
- Witch Hut
- Dungeons
- Desert Well
- Jungle Temple

The current implementation supports cancellation like trees for a possible future support of a StructureGeneratedEvent in GlowKit.

It should be noted that this PR is only based on building these structures, some structures like the witch hut or the jungle temple will need a nbt storage file and a structure mapping (this allows to place them in the terrain generation and not on the chunk population phase in order to have clean undecorated terrain to place the structures on) but this will be part of another PR.

DesertTemple

WitchHut

JungleTemple

### CODE REVIEW

**Comment by turt2live** [comment]
@jimmikaelkael psst. This doesn't merge thanks to the commit spam on master.

**Comment by jimmikaelkael** [comment]
@turt2live the funny thing is that it's one of my pulled PRs that conflicted :)

**Comment by jimmikaelkael** [comment]
@turt2live What would you suggest regarding the size of this PR ? add more structures now or let this PR be reviewed and maybe pulled first ?

**Comment by turt2live** [comment]
The number of structures is probably optimal for review as it is currently.

**Comment by jimmikaelkael** [comment]
@turt2live I'm letting a debug line mentioning coordinates where dungeons are generated so you can easily locate them. I didn't know how you could test the witch hut and jungle temple structures so I added a biome decorator for each of them (JungleTempleDecorator and WitchHutDecorator) but they clearly need to be removed before it's pulled as this isn't the way these structures should be generated.

**Comment by turt2live** [comment]
@jimmikaelkael These issues will need to be addressed:
- [witch huts spawning on top of trees](http://i.turt2live.com/2ZmY.jpg)
- [tripple temples](http://i.turt2live.com/RJuD.jpg) _Is actually 3 temples, unlike what chat originally says_
- Loot in dungeons is too "good"
- Should be 0 - 2 chests in dungeons, not 2
- Chests should always be against the walls
- Huts and temples are too frequent
  - Wells and dungeons ok

**Comment by jimmikaelkael** [comment]
@turt2live As I've said earlier the witch hut and jungle temple decorators are just temporary: they shouldn't be pulled as is.
My next PR regarding structures will allow to spawn the witch hut and jungle temple from a populator that is called before the tree populator: this will stop witch hut to spawn on top of trees. Same goes for jungle temples: once nbt storage and proper way to spawn them is there it solves the double/triple spawning.

According to this: "To spawn a chest, the chosen block must be empty and must have a solid block on exactly one of its four sides." (source http://minecraft.gamepedia.com/Dungeon) it seems a chest is not forced to always be against a wall, it can simply next another chest. I agree that it shouldn't be against the spawner alone (that's probably because I place the spawner before the chests I guess).

Will make changes but I repeat that the jungle temple and witch huts decorators are just there so that we can see these structures in our tests.

**Comment by jimmikaelkael** [comment]
@turt2live I think I've fixed all listed issues.

**Comment by turt2live** [comment]
Sorry for the late response.

> As I've said earlier the witch hut and jungle temple decorators are just temporary: they shouldn't be pulled as is.

This implies that the PR is not ready and shouldn't be reviewed. Although Glowstone has some features which are partially implemented, I don't think it's logical to pull something that is dependent on another, future, PR. 

Considering that future PR is also dependent on this one, I think it's best to merge the two. It does increase the amount of time it takes to review it, but it does make sure that we don't get pull in half-done features (overlapping structures is not appropriate).

**Comment by jimmikaelkael** [comment]
@turt2live that was the amount of code that made me feel worried, but I agree that it should be merged. I'll do this asap.

**Comment by jimmikaelkael** [comment]
Closing this as it's merged in #564.

**Pull request closed without merging**
