### PR TITLE
Added support for executing commands at the server console

### PR DESCRIPTION
**Pull request by zhuowei**

### CODE REVIEW

**Comment by SpaceManiac** [comment]
I will be looking into adding support for the [jline](http://jline.sourceforge.net/) library as soon as I can but will merge this tomorrow in the meantime. Thanks :)

**Comment by zhuowei** [comment]
OK, now it uses jLine; however, I don't know how to add command completion because I can't seem to find a way to access all registered commands.

**Comment by zhuowei** [comment]
Never mind, used reflection to access the knownCommands Map in SimpleCommandMap.

**Comment by SpaceManiac** [comment]
Merged and mashed into 160643018d0e9f3dc23958b36d1a6584aa2d68cf. Thanks! Will be doing coloring improvements shortly.

**Pull request closed without merging**
