### PR TITLE
Chest animations (Open/Close)

### PR DESCRIPTION
**Pull request by wow4201**
Sends the chest open and close animations. Tested, works as intended. Player can only open an unopened chest. Chest only closes when the player leaves the chest inventory.

### CODE REVIEW

**Comment by Ribesg** [comment]
Indentation is broken. Also you should cast only once, store a local reference to the cast if multiple uses are needed.

**Comment by nevercast** [comment]
Where are the players tracked when multiple players have a chest open?

If Alice opens the chest and then Bob starts using it also, then Alice closes it, the chest should not animate closed until Bob has finished.

**Comment by dequis** [comment]
This is a dead ticket, you know. wow4201 already ragequit weeks ago because he didn't feel like updating his stuff and blamed that on our PR handling.

**Comment by nevercast** [comment]
If the PR comes up again this one will likely be referenced, at which point they should take note that it needs to handle multiple players interacting with it at the same time. Earlier MC versions used a counter, later ones I believe track player GUIDs.

Though it was a bit of a grave dig, I'll keep a closer eye on dates.

**Pull request closed without merging**
