### PR TITLE
Add sponge block

### PR DESCRIPTION
**Pull request by socram8888**
This PR adds a general-purpose taxicab block iterator and employs it to add the block behaviour of sponges in 1.8.

Sponge working

### CODE REVIEW

**Comment by socram8888** [comment]
How did I manage to compile an Iterator without the remove method is beyond my own comprehension.

**Comment by Tonodus** [comment]
@socram8888 it's by default empty. (Java 8 default methods for interfaces)

**Comment by turt2live** [comment]
Incorrect drops for wet sponge. Also the naming of the iterator is kinda funny and doesn't seem to really apply to the definition of a taxicab number. I'm not sure on what else to call it though

**Comment by socram8888** [comment]
I called it TaxicabBlockIterator because in [MinecraftWiki](http://minecraft.gamepedia.com/Sponge), it says that "A sponge absorbs water around itself (water source blocks or flowing water) out to a **taxicab** distance of 7 in all directions". I'm open to suggestions, though.

**Comment by socram8888** [comment]
Drops have been fixed.

**Comment by dequis** [comment]
This fixes [#498](https://github.com/SpaceManiac/Glowstone/issues/498?)

<sub><sub>sorry i couldn't resist</sub></sub>

**Comment by turt2live** [comment]
This PR fails on edge cases. It also doesn't soak up the correct number of blocks.

Edge case:
edge

**Comment by socram8888** [comment]
That's how it's supposed to work, it will only scan if at least one **face** has water. That's why the wiki also says "taxicab", because it won't work for diagonals.

**Comment by socram8888** [comment]
This last PR not only improves performance but also it now absorbs the correct amount of water blocks.

**Comment by SpaceManiac** [comment]
Merged in 6e86a71dd994a867e3bbb34db09f8d8af2d8feb6.

**Pull request closed without merging**
