### PR TITLE
Handle target blocks gracefully.

### PR DESCRIPTION
**Pull request by JeromSar**
Sometimes, player.getTargetBlock() returns an IllegalStateException.
This is usually the case if players stand at height 127 and look up when left-clicking.
The exception can be safely caught and treated as an invalid block (air in this case).

### CODE REVIEW

**Comment by turt2live** [comment]
shouldn't the root cause be identified?

**Comment by JeromSar** [comment]
@turt2live The root cause is in fact the Bukkit API itself (see https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/util/BlockIterator.java#L170). This exception is thrown when the first block of the iteration can not be found. For example, when a player looks up, the first block would technically be outside the modifiable world.

For this particular case, I don't think it's necessary to change the Bukkit API. The change this pull request is minimal and avoids potential (and probable) errors when players swing their arms.

**Comment by turt2live** [comment]
It should be fixed in the Bukkit API for plugins calling the method...

**Comment by JeromSar** [comment]
@turt2live That would be an API breaking change. Additionally, it would require plugins to use the GlowStone-specific Bukkit, which is not GlowStone's goal (to be compatible with Bukkit plugins).

**Comment by turt2live** [comment]
@JeromSar This is breaking?

```
// Plugin code
try{
    Block block = null; // Return value from method in Bukkit
    block.stuff(); // throws NPE
}catch(Exception e){
    // ;o here we are
}
```

**Comment by JeromSar** [comment]
@turt2live You were a suggesting we fix the error in Bukkit, correct?

**Comment by turt2live** [comment]
Correct.

**Comment by JeromSar** [comment]
@turt2live Some plugins might depend on that error being thrown.

In this case, the `IllegalStateException` is purposely thrown. Catching the exception in Bukkit would be an API breaking change. 

See: https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/util/BlockIterator.java#L170

**Comment by turt2live** [comment]
I don't think a try/catch in Glowstone is suitable. Instead, Bukkit should be resolved or better handling on Glowstone's end should be implemented.

Currently in Bukkit there is no documentation on that exception being thrown.

**Comment by SpaceManiac** [comment]
Would love to see some concrete evidence that both plugins which don't handle this case themselves and plugins which do are likely to benefit from this change going into a Bukkit fork.

**Comment by JeromSar** [comment]
@SpaceManiac I don't believe this change should be implemented in Bukkit for that reason. For backwards compatibility, it's best to avoid touching Bukkit whenever possible.

@turt2live I could implement better pre-checking on GlowStone's end but that would imply a performance loss. It would be inefficient too as it would check if the starting block exists twice. This change is both simpler and future- and backwards compatible.

**Comment by turt2live** [comment]
It doesn't change the fact that it's a workaround. Workarounds are not ideal if a better solution can be implemented (and if there is no better solution, the problem should be looked at in more detail).

**Comment by turt2live** [comment]
Ticket: #172

**Comment by turt2live** [comment]
Sorry - bot fail :(

**Comment by turt2live** [comment]
After much deliberation with myself, I can't think of a better solution that would be less... meeeehhhh.

Looks good, I suppose.

**Comment by SpaceManiac** [comment]
Merged in 367f1b861861128a25fbe2d1ef44f1142822764e.

**Pull request closed without merging**
