### PR TITLE
Basic gravity for entities

### PR DESCRIPTION
**Pull request by ST-DDT**
This is the gravity similar to minecrafts one.
I'm not sure whether there are other things to consider like falling through blocks, but the velocity changes are done.

Even if this PR won't get pulled it may help other contributors to implement that feature.

Is there a template like Bukkit uses one for PRs?

Just for reference are my sources of that magic values:
https://github.com/Bukkit/mc-dev/blob/master/net/minecraft/server/EntityLiving.java#L1025-L1134
https://github.com/Bukkit/mc-dev/blob/master/net/minecraft/server/EntityArrow.java#L290-L336

### CODE REVIEW

**Comment by JeromSar** [comment]
There's some incorrect formatting in your PR. Mostly tabs that need to be replaced with spaces.

**Comment by ST-DDT** [comment]
Fixed

**Comment by ST-DDT** [comment]
I added my magic value references.

I also noticed that the "Entity" is not effected by gravity at all.
This implementation is based on the ArrowGravity.
This implementation almost matches LivingEntity one, but it looks like there isn't one `LIQUID_DRAG`, but `WATER_DRAG` and `LAVA_DRAG`

Here are the values for Arrow:
- `AIR_DRAG = 0.99`
- `WATER_DRAG = 0.8`
- `LAVA_DRAG = 0.8` (not 100% sure)
- `GRAVITY = 0.05`

Here are the values for LivingEntity:
- `AIR_DRAG = 0.91 * block.friction` (air friction = 1)
- `WATER_DRAG ~= 0.8`
- `LAVA_DRAG = 0.5`
- `GRAVITY = 0.02`

**Comment by turt2live** [comment]
I think this PR does some strange things to entities. Not confirmed yet though.

**Comment by turt2live** [comment]
@ST-DDT For whatever reason, I can 100% reproduce the following issues on a Glowstone server with ONLY this PR (done on a fresh server with a fresh world):
- Players are invisible to eachother
- Sometimes initial players are "stuck" at spawn locations visually

No idea how or why, but it happens.

**Comment by turt2live** [comment]
Sorry - bot fail :(

**Comment by turt2live** [comment]
@ST-DDT Github says this merges, however on the command line it does not. Please fix the issues as soon as possible, thanks!

**Comment by turt2live** [comment]
@ST-DDT Your PR is currently not mergable. Please resolve the merge conflicts as soon as possible, thanks!

`PR_BOT_CODE:1` (you can ignore this)

**Comment by turt2live** [comment]
@ST-DDT Your PR has not been mergable for at least 3.55134584538194 days! Please update your PR as soon as possible, thanks!

`PR_BOT_CODE:2` (you can ignore this)

**Comment by dequis** [comment]
Merged version: https://github.com/dequis/Glowstone/compare/pr-196

Newlines in glowplayer (-X renormalize), lombok changes in EntityStatusMessage, canSee renamed to canSeeEntity, and checkstyle fixes.

**Comment by dequis** [comment]
Oh, it's merged with master, this PR is against the entities branch. Whatever.

**Comment by turt2live** [comment]
@ST-DDT @dequis This PR is **still** not functional.

In order for this PR to continue, it must not send players to oblivion or any other related issues. 

One of the notable issues is that a player can walk around, but their server-side reference is at y=11000. 

Please resolve these issues as soon as possible. @ST-DDT if you are MIA or not interested in this, please take a second to comment on the PR at least.

**Comment by ST-DDT** [comment]
Im currently too busy to continur it but im still interedted in it. If you dont mind having thid Pr open a little bit longer i try to make it working in a cuple of days. Otherwise close it and i will open a new one if i solved the issues.

**Comment by dequis** [comment]
Awesome, ST-DDT lives!

Well, resubmitting against the `master` branch instead of `entities` would be cool. Then you can merge from my merge and save yourself some effort when you continue with it.

**Comment by turt2live** [comment]
I've set this as expired for the following reasons:
- The PR is potentially submitted to the wrong branch
- The PR content has been non-functional for 44 days
- The author appears to have abandoned this PR (please respond if incorrect)
- The pull request cannot be merged

Assigned to @SpaceManiac for review.

(Sorry for the bot spam)

**Comment by SpaceManiac** [comment]
> Otherwise close it and i will open a new one if i solved the issues.

Closing for inactivity and incompleteness but feel free to open another PR if/when you continue it.

**Pull request closed without merging**
