### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by gdude2002** [comment]
I sincerely hope this is a joke.

**Comment by gdude2002** [comment]
To clarify, this is the American spelling because most of the developers use that spelling, and the Bukkit API also uses that spelling. This is not a typo - it is intentional

(Ironically, you made a typo yourself. See if you can find it!)

**Comment by ethsmith** [comment]
Lol I be the knew that Americans spelled it like that xD

**Comment by ghost** [comment]
Did I? I only changed three words. Well, it was a joke, lol
(If it wasn't, I would have gone and changed all the affected classes etc.)

**Comment by turt2live** [comment]
Jokes that waste time aren't funny.

**Comment by gdude2002** [comment]
> Jokes that waste time aren't funny.

Amen to that.

**Comment by ghost** [comment]
@turt2bot @gdude2002 Hehehe

**Pull request closed without merging**
