### PR TITLE
Gradle build improvement

### PR DESCRIPTION
**Pull request by ghost**
*Final jar name will have now build version.
*Cleaned unnecessary "ext" part from variables.

### CODE REVIEW

**Comment by gdude2002** [comment]
I can't figure out how to merge this on Bamboo. Any help appreciated.

**Comment by turt2live** [comment]
Ignore Bot.

**Comment by dequis** [comment]
@gdude2002 Mirrored it in an actual fork here, if it helps. https://github.com/dequis/Glowstone/compare/pr-407

**Comment by ghost** [comment]
Sorry about unknown repository. Edited with github editor.

**Comment by SpaceManiac** [comment]
@gdude2002 If you need a general solution, the ref `pull/XXX/head` on this repository can be used to refer to the commit regardless of other shenanigans.

I don't think there's much benefit to specifying the shadowed jar's classifier. The `-remapped.jar` is the one that should be used anyways and it's not great to have inconsistent build output paths.

The removal of the `ext.` references works in Gradle 1.10, but are they okay on Gradle 2.0?

**Comment by ghost** [comment]
@SpaceManiac Working with 2.1 for me.

Gradle default naming: 

```
${baseName}-${appendix}-${version}-${classifier}.${extension}
```

Maybe than we can just add in `$version` build version? 

```
shadowJar {
    dependencies {
        exclude(dependency(lombok))
    }

    version = version + gitDescribe
}
```

**Comment by SpaceManiac** [comment]
What advantage does including the fancy version string in the jar filename give?

**Comment by ghost** [comment]
@SpaceManiac better version controlling i guess?

**Comment by SpaceManiac** [comment]
I'll keep the `ext.` removal in mind next time I work on the `build.gradle`, but I would prefer not to mess with the jar filenames. Thanks for your time anyways!

**Pull request closed without merging**
