### PR TITLE
[WIP] Fix drops for blocks that should break instantly

### PR DESCRIPTION
**Pull request by jimmikaelkael**
Fixes issue #384.

### CODE REVIEW

**Comment by jimmikaelkael** [comment]
While this fixes the problem, I'm not sure it is the best solution...

Don't we need to have Material hardnesses in the block registry instead ?
This could help to prevent a malicious client from digging too fast for example.

**Comment by SpaceManiac** [comment]
I think I agree it would be beneficial to go ahead and work in material hardness into the registry somehow, which solves this and other weirdness with block hardness (e.g. #372) in one fell swoop, as well as finally adding that cheat prevention.

**Comment by jimmikaelkael** [comment]
OK, I'll try to modify this PR to conform that.
Is a chained method call suitable to set the hardnesses ?

**Comment by jimmikaelkael** [comment]
I've rebased to something like we discussed above.
Tell me if this is what we need, and I'll set other blocks hardness values.

**Comment by SpaceManiac** [comment]
My main concerns are:
- `public setHardness` on BlockType - should somehow be finagled to not be public, IMO.
- `reg` in ItemTable returning the type. I think instead if `setHardness` stays like it is it should return `this` and the reg call should look like `reg(new XYZ().setHardness(2));`.
- `getHardness()` in GlowBlock. Maybe instead add a general-purpose `getBlockType` that looks up the `BlockType`, and call `.getBlockType().getHardness().`? This could then be used other places complicated `ItemTable` calls are currently used.

I need to give `ItemTable` a solid once-over for 1.8 anyways (see #379), so some of the issues above could be deferred until later.

**Comment by Tonodus** [comment]
I think we should swap the hardness value along with other block-related values (f.e. blast resistance, light-level, and so on).
If we'd hardcode all this values in ItemTable that'd be hard to maintain.

**Comment by jimmikaelkael** [comment]
This is not something that will change regularly... Most if not all will never change.

**Comment by jimmikaelkael** [comment]
Rebased again with changes like we discussed above.
EDIT:
I'll add the other blocks hardness values and appropriate javadoc if this fix is convenient.

About setHardness being public in BlockType, it could be protected but then no way to call it from ItemTable directly...

**Comment by jimmikaelkael** [comment]
Commited all blocks hardness values, for those already implemented in Glowstone of course.

**Comment by Tonodus** [comment]
Setting the hardness value from ItemTable is not such a good approach IMO:

Blocks have many other values along with hardness, as said light-level, blast resistance, map-color, whether they are ignitable, and probably more I haven't in mind; the amount will increase with MC updates I assume.

The ItemTable isn't the right place to set all this values. They are all final, so it'd be good if there were no setter.
Instead I'd prefer a general class managing all this values and the mapping to the different Materials/Blocks.
Another approach would be public abstract getters for this values in BlockType; the value setting would be implemented then in the respective implementations of BlockType.

**Comment by jimmikaelkael** [comment]
@Tonodus So something like what is done with recipes would be good to you ?

**Comment by Tonodus** [comment]
@jimmikaelkael IMO the recipe solution is quite nice and could be used for this, too. So yes.

**Comment by jimmikaelkael** [comment]
@Tonodus Anyway the 2nd approach you mentionned is not feasible IMO.
How would you handle the BlockType implementations when it's instanciated for several material then ?
I prefer the 1st approach.

**Comment by turt2live** [comment]
It looks like this PR still has some discussion about approach going on. If there's a lot to do, please mark it as a WIP by prepending `[WIP]` to the title. If there is just some minor things to do, feel free to ping me using @turt2live when this PR can be thrown through testing. Thanks!

**Comment by jimmikaelkael** [comment]
I think this should now be based on the new blocks branch.
EDIT: not sure... The content of commit b431f69 on master should be sufficient to start with.

**Comment by SpaceManiac** [comment]
I wouldn't recommend it right now, the blocks branch isn't really final at all yet.

**Comment by gdude2002** [comment]
Failing: http://bamboo.gserv.me/browse/GLOW-SRV-PR385-91

**Comment by dequis** [comment]
Hm, the merge conflict is because 3166294b added `reg(Material.ENDER_PORTAL_FRAME, new BlockEnderPortalFrame());` to ItemTable.java, but since this PR changes pretty much all the block registry lines, sounds like you have to deal with this with every single change to that file while the PR is open.

Have fun with that!

(Actually I guess it's not a huge deal once you're used to it - it's a single conflict that looks ugly until you know what to do)

**Comment by jimmikaelkael** [comment]
I'm rather busy with bonemeal/farming related PRs, but I'll solve this ASAP.

**Comment by turt2live** [comment]
@jimmikaelkael psst. This doesn't merge thanks to the commit spam on master.

**Comment by jimmikaelkael** [comment]
This PR is in standby as I've a lot of work with the Structures PR. At everyone: feel free to code a better alternative.

**Comment by jimmikaelkael** [comment]
Closing this in favor of #541.

**Pull request closed without merging**
