### PR TITLE
Add "server.ip: 0.0.0.0" to default glowstone.yml

### PR DESCRIPTION
**Pull request by bendem**
Because there are quite a few people asking about it and I don't think it costs anything to add it there.

### CODE REVIEW

**Comment by SpaceManiac** [comment]
I notice a difference in the startup log with this PR applied, likely due to the difference between `ip: ''` and `ip: 0.0.0.0`:

Before: `Binding to address: 0.0.0.0/0.0.0.0:25565...`
After: `Binding to address: /0.0.0.0:25565...`

There appears to be no functional difference, but I was wondering if there's a specific reason you chose `0.0.0.0` instead of the current default blank value which resolves to `InetAddress.anyLocalAddress()`?

**Comment by dequis** [comment]
`ip: ''` would also listen in ipv6, if available. Unless there's a possibility that `InetAddress.anyLocalAddress()` hands out an address that isn't supported by the system - and i hope nobody has fucked up their ipv6 stack that much - that would be preferable.

**Comment by bendem** [comment]
I used 0.0.0.0 because I thought it'd be a nice functional placeholder. I'll change it when I get home.

**Comment by dequis** [comment]
...this seriously doesn't need testing.

**Comment by SpaceManiac** [comment]
Merged in ~~281e3c1~~ 6cafd1d.

**Comment by bendem** [comment]
in 6cafd1d6fd5824034fc16dc229935e8f25eedbf5 actually :wink:

**Comment by hintss** [comment]
@dequis test all the things

**Pull request closed without merging**
