### PR TITLE
Renamed net package to network

### PR DESCRIPTION
**Pull request by ghost**
For more intuitively understanding

### CODE REVIEW

**Comment by mastercoms** [comment]
Why? this doesn't do anything what so ever to further glowstone, and might break things.

**Comment by Postremus** [comment]
I think it is inuitive enoug as it is, because java has a "java.net"
package, too.

2014-09-27 23:21 GMT+02:00 Vladislavs Golubs notifications@github.com:

**Comment by Tonodus** [comment]
Git doesn't handle file/folder renaming. As such this PR causes much trouble with the history of the related files, PR/forks working on this files etc. It isn't worth it IMO.

**Comment by daboross** [comment]
'net' doesn't really mean much else besides network. In this context, I don't really see how it is any less intuitive. Plus, changing the package breaks any external stuff using Glowstone's internal networking, and messes with a ton of file history diffs.

**Comment by ghost** [comment]
'net.glowstone.net' sounds weird

**Comment by Wild1145** [comment]
It might just be me, but I see no file changes and infinite commits...

**Comment by Tonodus** [comment]
@Wild1145 Seems like he deleted that commits.

**Comment by mastercoms** [comment]
@ensirius Could you close this pull request if there is nothing to merge?

**Pull request closed without merging**
